version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5333:5432

volumes:
  pgdata: